ifneq (,$(filter test_utils_interactive_sync,$(USEMODULE)))
  USEMODULE += stdin
endif

# This allows registering a function that will be automatically called
ifneq (,$(filter test_utils_interactive_sync_autocall,$(USEMODULE)))
  USEMODULE += core_pre_main_function
  USEMODULE += test_utils_interactive_sync
endif
