INCLUDES += -I$(RIOTCPU)/msp430_common/include/

# export the CPU model
MODEL := $(shell echo $(CPU_MODEL) | tr 'a-z' 'A-Z')
CFLAGS += -DCPU_MODEL_$(MODEL)

UNDEF += $(BINDIR)/msp430_common/startup.o

USEMODULE += msp430_common msp430_common_periph
USEMODULE += periph_common

DEFAULT_MODULE += oneway_malloc

# include the msp430 common Makefile
include $(RIOTMAKE)/arch/msp430.inc.mk
