# the granularity of provided feature definition for STMs is currently by CPU
# sub-family (e.g., stm32f[1234]).  Unfortunately, only some of e.g., the
# stm32f4 have an RNG peripheral.  As during evaluation of the features , no
# CPU variable is available, we need to filter by board.
#
ifeq (,$(filter nucleo-f401re nucleo-f411re nucleo-f446re nucleo-f446ze,$(BOARD)))
  FEATURES_PROVIDED += periph_hwrng
endif

-include $(RIOTCPU)/stm32_common/Makefile.features
