ifneq (,$(filter microbit,$(USEMODULE)))
  USEMODULE += xtimer
  USEMODULE += mineplex
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

ifneq (,$(filter netdev_default,$(USEMODULE)))
  USEMODULE += nrfmin
endif
