# INCLUDES += -I$(PKGDIRBASE)/wolfmqtt/wolfmqtt
# INCLUDES += -I$(PKGDIRBASE)/wolfmqtt/examples
# INCLUDES += -I$(RIOTBASE)/pkg/wolfmqtt/include

DIRS += $(RIOTPKG)/wolfmqtt/contrib
DIRS += $(RIOTPKG)/wolfmqtt/wolfmqtt
DIRS += $(RIOTPKG)/wolfmqtt/examples
DIRS += $(RIOTPKG)/wolfmqtt/src
