# Have wolfmqtt headers available as 'wolfmqtt/mqtt_client.h' for example
# and examples files as 'wolfmqtt_examples/header.h'
INCLUDES += -I$(PKGDIRBASE)/wolfmqtt
# Have RIOT package headers available
INCLUDES += -I$(RIOTBASE)/pkg/wolfmqtt/include

DIRS += $(RIOTPKG)/wolfmqtt/contrib
