FEATURES_PROVIDED += periph_cpuid
FEATURES_PROVIDED += periph_gpio periph_gpio_irq
FEATURES_PROVIDED += puf_sram
FEATURES_PROVIDED += periph_uart_modecfg
FEATURES_PROVIDED += periph_wdt
FEATURES_PROVIDED += periph_timer_overflow

ifneq (,$(filter $(BOARDS_WITHOUT_HWRNG),$(BOARD)))
  FEATURES_PROVIDED := $(filter-out periph_hwrng,$(FEATURES_PROVIDED))
endif

-include $(RIOTCPU)/cortexm_common/Makefile.features
