USEMODULE += cortexm_common
USEMODULE += periph
USEMODULE += cortexm_common_periph

# all cortex MCU's use newlib as libc
USEMODULE += newlib
# use the nano-specs of Newlib when available
USEMODULE += newlib_nano
