FEATURES_PROVIDED += periph_eeprom
FEATURES_PROVIDED += periph_flashpage
FEATURES_PROVIDED += periph_flashpage_raw

ifeq (,$(filter nucleo-l031k6,$(BOARD)))
  FEATURES_PROVIDED += periph_hwrng
endif

-include $(RIOTCPU)/stm32_common/Makefile.features
